server:
  port: 8082
spring:
  application:
    name: transaction-service
  profiles:
    active: development
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://mysql:3306/transaction_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      hibernate:
        format_sql: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
