server:
  port: 8084
spring:
  application:
    name: user-service
  profiles:
    active: development
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://mysql:3306/user_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
